config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'static_pages/promociones'

  get 'static_pages/autos'

  get 'static_pages/locaciones'

  get 'static_pages/paylessclub'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def promociones
  end

  def autos
  end

  def locaciones
  end

  def paylessclub
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Renta de Autos en México"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container nav-top">
      <p class="phones">MEX (800) 772 9537</p><p class="phones phone-2">US (800) 750 7099</p>
        <%= link_to "ENG",   "https://www.paylesscar.com", class: "lang-link"%>
        <nav>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav navbar-right nav-bottom">
              
              <li><%= link_to "Iniciar sesión",   root_path, class: "menu-obj" %></li>
              <li><%= link_to "Registro",   static_pages_promociones_path, class: "menu-obj" %></li>
              <li><%= link_to "Atención a clientes", static_pages_autos_path %></li>
            <form class="navbar-form navbar-left">
               <div class="form-group">
                  <input type="text" class="form-control buscar" placeholder="Buscar">
               </div>
                <button type="submit" class="fa fa-search search"></button>
            </form>
            </ul>
          </div>
        </nav>
      </div>

      <nav class="navbar navbar-default">
  <div class="container-fluid  nav-top">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to image_tag("payless-logo.png", alt: "logo"), 'https://paylesscar.com.mx', class: 'logo' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right main-menu-items">
        <li><%= link_to "Iniciar sesión",   root_path, class: "menu-obj visible-xs-block" %></li>
        <li><%= link_to "Registro",   static_pages_promociones_path, class: "menu-obj visible-xs-block" %></li>
        <li><%= link_to "Atención a clientes", static_pages_autos_path, class: "visible-xs-block" %></li>
        <li><%= link_to "Reservaciones",   root_path, class: "main-menu" %></li>
        <li><%= link_to "Promociones",   static_pages_promociones_path, class: "main-menu" %></li>
        <li><%= link_to "Autos",   static_pages_autos_path, class: "main-menu" %></li>
        <li><%= link_to "Locaciones",   static_pages_locaciones_path, class: "main-menu" %></li>
        <li><%= link_to "Payless club",   static_pages_paylessclub_path, class: "main-menu" %></li>
         <form class="navbar-form navbar-left visible-xs-block">
               <div class="form-group">
                  <input type="text" class="form-control buscar" placeholder="Buscar">
               </div>
                <button type="submit" class="fa fa-search search"></button>
            </form>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <!-- jQuery library -->
    
    <!--[if lt IE 9]>
       <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
       </script>
    <![endif]-->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
   
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/autos.html.erb
<h1>StaticPages#autos</h1>
<p>Find me in app/views/static_pages/autos.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Payless") %>
<div class="half-color">
    <div class="container top-content">
        <div class="row">
	        <div class="col-md-6 search-eng">
	           	<h2>
	           	 	Encuentra las mejores ofertas en coches de alquiler.
	           	</h2>
	           	    <form role="form" action="" method="">
	                    <div id="contact-form" class="form-container" data-form-container>
	                        <br>
							    <div class="input-group">
								  <input type="text" class=" input-lg form-control" placeholder="Aeropuerto / Ciudad o escoge tu locación" aria-describedby="basic-addon2">
								  <span class="input-group-addon" id="basic-addon2"><i class="fa fa-map-marker" aria-hidden="true"></i></span>
							    </div>
							    <br>
							    <div class="row">
								    <div class="col-sm-3">
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2">
										  <span class="input-group-addon" id="basic-addon2"><i class="fa fa-calendar" aria-hidden="true"></i></span>
										</div>
								    </div>
								    <div class="col-sm-3">
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2">
										  <span class="input-group-addon" id="basic-addon2"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
										</div>
								    </div>
									<div class="col-sm-3">
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2">
										  <span class="input-group-addon" id="basic-addon2"><i class="fa fa-calendar" aria-hidden="true"></i></span>
										</div>
									</div>
									<div class="col-sm-3">
										<div class="input-group">
										  <input type="text" class="form-control" placeholder="" aria-describedby="basic-addon2">
										  <span class="input-group-addon" id="basic-addon2"><i class="fa fa-clock-o" aria-hidden="true"></i></span>
										</div>
								    </div>
								</div>
								<br>
								<div class="input-group">
								        <input type="checkbox" aria-label="Checkbox for following text input">
								      	<span>Regresar a otro lugar</span>
								</div>	
								<br>
								<div class="row">
									<div class="col-sm-4">
										<div class="form-group">
										  <select class="form-control" id="sel1">
										    <option>1</option>
										    <option>2</option>
										    <option>3</option>
										    <option>4</option>
										  </select>
										</div>
									</div>
									<div class="col-sm-8">
										<div class="form-group">
										  <select class="form-control" id="sel1">
										    <option>1</option>
										    <option>2</option>
										    <option>3</option>
										    <option>4</option>
										  </select>
										</div>
									</div>
								</div>
								<input type="submit" class="btn btn-info" value="Submit Button">
							<br>
							<div class="input-group checkbx">
								<input type="checkbox" aria-label="Checkbox for following text input">
								    <span> Tengo un código de cupón / PDN</span>
							</div>
							<div class="input-group checkbx">
								<input type="checkbox" aria-label="Checkbox for following text input">
								    <span> ¿Es usted un agente de viajes / Perks Member?</span><i class="fa fa-question" aria-hidden="true"></i>
							</div>

	                    </div>
					</form>
	           
	        </div>
           <div class="col-sm-6">
           	  <h2 class="catch-eye"><strong>Ingrese</strong> a su cuenta de <span class="brand-txt">Payless</span> para obtener tarifas exclusivas</h2>
           	  <%= link_to image_tag("nissan-march.png", alt: "Nissan March"), 'https://paylesscar.com.mx', class: 'img-responsive march' %>
           </div>

    	</div>
    </div>
</div>

<!-- INICIA PROMOCIONONES -->

<div class="gray">
	<div class="container promociones">
	<div class="content-area">
		<div id="myCarousel" class="carousel slide">
		  <!-- Indicators -->
		  	<ol class="carousel-indicators">
			    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
			    <li data-target="#myCarousel" data-slide-to="1"></li>
			    <li data-target="#myCarousel" data-slide-to="2"></li>
		    </ol>

		  <!-- Wrapper for slides -->
		    <div class="carousel-inner">
			    <div class="item active">
					<div class="row promo">
						<div class="col-sm-6 promos">
						  <h2 class="blue-title">Promociones</h2>
						  <br>
						  <br>
						  <h2>Lorem ipsum dolor sit amet</h2>
						  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br> Ut ornare orci ac commodo ultricies. Aliquam erat volutpat.</p>
						  <br>
						  <br>
						  <button class="info">Más información</button>
						</div>
						<div class="col-sm-6">
							<div class="price">$19</div>
							<div class="orange">
							  <p>Lorem ipsum dolor sit amet</p>
						    </div>
						    <div class="march-1">
						    	 <%= link_to image_tag("nissan-march.png", alt: "Nissan March"), 'https://paylesscar.com.mx', class: 'img-responsive' %>
						    </div>	
						</div>
					</div>
				</div>
				<div class="item">
		           <div class="row promo">
						<div class="col-sm-6 promos">
						  <h2 class="blue-title">Promociones</h2>
						  <br>
						  <br>
						  <h2>Lorem ipsum dolor sit amet</h2>
						  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br> Ut ornare orci ac commodo ultricies. Aliquam erat volutpat.</p>
						  <br>
						  <br>
						  <button class="info-1">Más información</button>
						</div>
						<div class="col-sm-6">
							<div class="price">$19</div>
							<div class="blue">
							  <p>Lorem ipsum dolor sit amet</p>
						    </div>
						    <div class=jeep>
						    	 <%= link_to image_tag("jeep-wrangler.png", alt: "Jeep wrangler"), 'https://paylesscar.com.mx', class: 'img-responsive' %>
						    </div>	
						</div>
					</div>
		        </div>
			    <div class="item">
			       <div class="row promo">
						<div class="col-sm-6 promos">
						  <h2 class="blue-title">Promociones</h2>
						  <br>
						  <br>
						  <h2>Lorem ipsum dolor sit amet</h2>
						  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br> Ut ornare orci ac commodo ultricies. Aliquam erat volutpat.</p>
						  <br>
						  <br>
						  <button class="info-2">Más información</button>
						</div>
						<div class="col-sm-6">
							<div class="price">$19</div>
							<div class="green">
							  <p>Lorem ipsum dolor sit amet</p>
						    </div>
						    <div class="vento">
						    	 <%= link_to image_tag("vento.png", alt: "Vento"), 'https://paylesscar.com.mx', class: 'img-responsive' %>
						    </div>	
						</div>
					</div>
			    </div>
		    </div>
		</div>

    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
						    <span class="icon-prev"></span>
						</a>
						<a class="right carousel-control" href="#myCarousel" data-slide="next">
						    <span class="icon-next"></span>
						</a>
	</div>
	</div>
</div>
<!-- Autos -->
<div class="container autos">
  <div>
  	<center><h2 class="blue-title title-mobil">Autos</h2></center>
  </div>
	  <div class="row">
	  	<div class="col-sm-4 col-mob-1">
			
		    <div class="lil-price">consectetur adipiscing</div>
			<div class="lil-blue">
			  <p>Lorem ipsum dolor sit amet</p>
		    </div>
		    <div class="lil-jeep">
		    	 <%= link_to image_tag("jeep-wrangler.png", alt: "Jeep wrangler"), 'https://paylesscar.com.mx', class: 'img-responsive' %>
		    </div>	
	  	</div>
	  	<div class="col-sm-4 col-mob-1 autos-1">
	  		<div class="lil-price">consectetur adipiscing</div>
			<div class="lil-orange">
			  <p>Lorem ipsum dolor sit amet</p>
		    </div>
		    <div class="lil-march-1">
		    	 <%= link_to image_tag("nissan-march.png", alt: "Nissan March"), 'https://paylesscar.com.mx', class: 'img-responsive' %>
		    </div>
	  	</div>
	  	<div class="col-sm-4 col-mob-1 autos-1">
	  		<div class="lil-price">consectetur adipiscing</div>
			<div class="lil-green">
			  <p>Lorem ipsum dolor sit amet</p>
		    </div>
		    <div class="lil-vento">
		    	 <%= link_to image_tag("vento.png", alt: "Vento"), 'https://paylesscar.com.mx', class: 'img-responsive' %>
		    </div>	
	  	</div>
	  </div>	
</div>


<!-- Locaciones -->

<div class="mapa">
   <div class="circle"></div><h2 class="locations">Locaciones</h2>
    <div id ="maps" class="embed-container maps" style="width: 100%; height: 500px;">
	<%= javascript_include_tag "maps" %>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUt_UmWQlRNc8oYEavw_pX9TW5gJKib5o&callback=initMap">
    </script>
</div>

app/views/static_pages/locaciones.html.erb
<h1>StaticPages#locaciones</h1>
<p>Find me in app/views/static_pages/locaciones.html.erb</p>

app/views/static_pages/promociones.html.erb
<h1>StaticPages#promociones</h1>
<p>Find me in app/views/static_pages/promociones.html.erb</p>